language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - lts/*

script:
  - npm run build
  - node build.js --all --e2e
  - node build.js --all --test
  - node build.js --all --e2e --json
  - node build.js --all --test --json
  - node build.js --all --e2e --json --sourcemap
  - node build.js --all --test --json --sourcemap
  - node dist/bin/cli.js stats.e2e.json
